name: fd
adopt-info: fd
summary: fd is a program to find entries in your filesystem
description: |
  fd is a program to find entries in your filesystem. It is a simple, fast and user-friendly
  alternative to find. While it does not aim to support all of find's powerful functionality, it
  provides sensible (opinionated) defaults for a majority of use cases.
  
license: MIT

base: core20
grade: stable
confinement: strict

architectures:
  - build-on: [amd64, armhf, arm64, ppc64el, s390x]
    
assumes:
  - command-chain
  
apps:
  fd: 
    command: bin/fd      
    command-chain: 
      - bin/homeishome-launch      
    plugs:
      - home
      

parts:
  fd:
    plugin: rust
    source: https://github.com/sharkdp/fd
    source-type: git

    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"

  homeishome-launch:
    plugin: nil
    stage-snaps:
      - homeishome-launch 
